// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTNPpzeEs3pxoxhz5kTf-NWVIOPpeoMcw',
    appId: '1:987638875582:web:a03d4421147a2bff40a5ef',
    messagingSenderId: '987638875582',
    projectId: 'lung-care-plus-c04f5',
    authDomain: 'lung-care-plus-c04f5.firebaseapp.com',
    storageBucket: 'lung-care-plus-c04f5.firebasestorage.app',
    measurementId: 'G-NE8SYRG3V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJEf1MityiRa5K22MoaYKj0IRFvd5UlGw',
    appId: '1:987638875582:android:8ba1aee63abc233640a5ef',
    messagingSenderId: '987638875582',
    projectId: 'lung-care-plus-c04f5',
    storageBucket: 'lung-care-plus-c04f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh_2TAuT3Qn10aMbqqmYJ3CPenCXx0q7o',
    appId: '1:987638875582:ios:d1b1e2acb36b41ea40a5ef',
    messagingSenderId: '987638875582',
    projectId: 'lung-care-plus-c04f5',
    storageBucket: 'lung-care-plus-c04f5.firebasestorage.app',
    iosBundleId: 'com.example.lungCareMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh_2TAuT3Qn10aMbqqmYJ3CPenCXx0q7o',
    appId: '1:987638875582:ios:d1b1e2acb36b41ea40a5ef',
    messagingSenderId: '987638875582',
    projectId: 'lung-care-plus-c04f5',
    storageBucket: 'lung-care-plus-c04f5.firebasestorage.app',
    iosBundleId: 'com.example.lungCareMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTNPpzeEs3pxoxhz5kTf-NWVIOPpeoMcw',
    appId: '1:987638875582:web:3d3f5ee04ff067dd40a5ef',
    messagingSenderId: '987638875582',
    projectId: 'lung-care-plus-c04f5',
    authDomain: 'lung-care-plus-c04f5.firebaseapp.com',
    storageBucket: 'lung-care-plus-c04f5.firebasestorage.app',
    measurementId: 'G-BT4LHVHT5J',
  );
}
